### PR TITLE
update to reflect internal number type

### PR DESCRIPTION
**Pull request by ros3bud**

### CODE REVIEW

**Comment by ros3bud** [comment]
Further changes added to this branch to complete the update of mortgage.loan.amount to range type. Approved of by @cgrayson. Going to wait to merge until all are ready.

**Comment by ros3bud** [comment]
@alexkwolfe, LGTY? 
Changed the internal type back to number and got rid of test for range.

**Comment by ros3bud** [comment]
Reverted to number - @alexkwolfe, LGTY?

**Comment by alexkwolfe** [comment]
LGTM

**Pull request merged**
